name: Auto Close Config PRs

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  pull-requests: write
  issues: write

jobs:
  auto-close:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR for 'Update config.json'
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const text = (pr.title + " " + (pr.body || "")).toLowerCase();

            // Target phrase
            const keyword = "update config.json";

            if (text.includes(keyword)) {
              const prNumber = pr.number;

              // Add a polite comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: "💡 **Dear user**, Don't share your private config info to us. Thanks ❤️‍🩹"
              });

              // Close the PR
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber,
                state: "closed"
              });

              console.log(`🚫 Closed PR #${prNumber} because it contained 'Update config.json'.`);
            } else {
              console.log("✅ No sensitive keywords found. PR allowed.");
            }
